# Generated by Django 5.2.1 on 2025-08-27 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_printdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='printdesign',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='printdesign',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='printdesign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='print_designs/'),
        ),
        migrations.AlterField(
            model_name='printdesign',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='socialmediadesign',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='socialmediadesign',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_media/'),
        ),
        migrations.AlterField(
            model_name='socialmediadesign',
            name='platform',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialmediadesign',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
