# Generated by Django 5.2.1 on 2025-08-27 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='khalti_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
